workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 90
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      machine:
        type: mac_mini_m1
      vars:
        GRADLE_OPTS: "-Xmx12G -XX:MaxMetaspaceSize=6G -XX:+UseG1GC -XX:+UseStringDeduplication"
        JAVA_OPTS: "-Xmx12G -XX:MaxMetaspaceSize=6G"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Update CocoaPods specs
        script: |
          pod repo update
      - name: Install iOS dependencies
        script: |
          cd ios && pod install --repo-update
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Build Android (for testing)
        script: |
          flutter build apk --release --target-platform android-arm64 --split-per-abi --obfuscate --split-debug-info=build/app/outputs/symbols
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/Runner.app
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Testers"